client and server done
fi1atov/go_otus_hw pull request #13
Opened 2024-03-24 20:54 UTC by fi1atov

## Домашнее задание №13 «HTTP клиент и сервер»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - server.go ~150 строк
  - client.go ~100 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-03-27 05:38 UTC, vladislavmass requested changes

2024-03-27 05:38 UTC, vladislavmass commented on hw13_http/server/server.go
> +		fmt.Fprintf(w, "Only GET and POST methods are supported.")
Не надо возвращать текст.  Для таких случаев в RFC существует http status 405.

2024-03-27 05:38 UTC, vladislavmass commented on hw13_http/server/server.go
> +	http.HandleFunc("/hello", hello)
Слушать нужно корневой путь, а не hello

2024-03-27 05:38 UTC, vladislavmass commented on hw13_http/server/server.go
> +	switch r.Method {
Реализации методов get и post бесполезны. Лучше распарсите аргументы запросов, выведите их в консоль и отправьте это обратно. Будет такой эхо сервер

2024-03-31 18:12 UTC, fi1atov commented on hw13_http/server/server.go
> +		fmt.Fprintf(w, "Only GET and POST methods are supported.")
Поправил. Теперь возвращаю 405 если указан недопустимый метод. Проверил с помощью Postman

2024-03-31 18:12 UTC, fi1atov commented on hw13_http/server/server.go
> +	http.HandleFunc("/hello", hello)
Поправил

2024-03-31 18:14 UTC, fi1atov commented on hw13_http/server/server.go
> +	switch r.Method {
Сделал. Для GET-запросов извлекаю query-параметры из URL и возвращаю клиенту.
Для Post-запросов извлекаю из тела json - читаю его и возвращаю пользователю.
Тестировал также в Postman

2024-03-31 18:32 UTC, vladislavmass approved these changes

2024-04-03 21:27 UTC, merged