HW3 is completed
fi1atov/go_otus_hw pull request #2
Opened 2024-01-02 17:51 UTC by fi1atov

## Домашнее задание №3 «Шахматная доска»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~25 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-01-02 18:50 UTC, vladislavmass requested changes
Хорошая начало, интересная реализация. Но неверное имя модуля в файле go.mod мешает принять работу, а также хотелось бы что бы реализовали переиспользование строки

2024-01-02 18:50 UTC, vladislavmass commented on hw03_chessboard/main.go
> +		for y := 1; y <= size-1; y++ {
Зачем формировать одну и туже строку на каждом шаге, что мешает сформировать ее заранее и переиспользовать?

2024-01-02 21:17 UTC, fi1atov commented on hw03_chessboard/main.go
> +		for y := 1; y <= size-1; y++ {
У меня сложность в том, что если использовать одну и ту же сформированную строку, например "# # # # " управляя сдвигом, просто добавляя вначале строки пробел через каждую итерацию, то идеальной доски не получится. Получаются лишние пробелы в конце строк через каждую итерацию, т.к. переиспользуемая строка содержит в конце пробел.
Вот так будет получаться (для наглядности заменил пробелы на букву "a").
```
#a#a#a#a
a#a#a#a#a
#a#a#a#a
a#a#a#a#a
```

А нужно чтобы было так, как я понял:
```
#a#a#a#a
a#a#a#a#
#a#a#a#a
a#a#a#a#
```


Переделал немного работу. Теперь я конкатенирую каждый добавляемый символ к формируемому результату.

2024-01-03 03:29 UTC, vladislavmass approved these changes
Хорошая работа. Хотя первый вариант был более выигрышным по производительности из за того что строки в go неизменяемый объект и при конкатенации происходит аллкокация новой памяти и копирование в нее данных

2024-01-03 07:41 UTC, fi1atov commented
Спасибо за комментарии!
Почитаю подробнее про эти функции:
strings.Builder
template.WriteRune
template.String

Насчет конкатенации также буду иметь ввиду на будущее, спасибо!

2024-01-03 07:41 UTC, merged