step 1
fi1atov/go_otus_hw pull request #8
Opened 2024-02-18 15:31 UTC by fi1atov

## Домашнее задание №9 «JSON и Pb сериализация»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~100 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-02-18 17:46 UTC, fi1atov commented on hw09_serialize/main.go
> +	protoRes, _ := proto.Marshal(&book)
Почему-то тут ошибка: cannot use &book (value of type *Book) as protoreflect.ProtoMessage value in argument to proto.Marshal: *Book does not implement protoreflect.ProtoMessage (missing method ProtoReflect)

2024-02-19 06:36 UTC, vladislavmass commented on hw09_serialize/main.go
> +	protoRes, _ := proto.Marshal(&book)
В данном случае идет попытка использовать структуру Book которая лежит в пакете main,  а она не реализует соответствующий интерфейс. Необходимо использовать структуру Book из файла data.pb.go и разобраться с именами папок и пакетов

2024-02-22 14:06 UTC, vladislavmass requested changes

2024-02-22 14:06 UTC, vladislavmass commented on hw09_serialize/main.go
> +// func deserializationPROTO(books []Book, data []byte) []*Book {
Зачем передавать books на вход?

2024-02-22 14:06 UTC, vladislavmass commented on hw09_serialize/main.go
> +// 	if err := proto.Unmarshal(data, &books); err != nil {
2 аргументом должен быть не books, а указатель на объект типа BooksList

2024-02-22 14:06 UTC, vladislavmass commented on hw09_serialize/main.go
> +// 	return books
Возвращать необходимо поле Content структуры BooksList

2024-02-23 06:37 UTC, vladislavmass requested changes

2024-02-23 06:37 UTC, vladislavmass commented on hw09_serialize/main.go
> +func SerializationPROTO(books *BooksList) []byte {
Аргумент должен иметь тип books []*Books

2024-02-23 06:37 UTC, vladislavmass commented on hw09_serialize/main.go
> +	res, err := proto.Marshal(books)
Перед вызовом Marshal вам нужно сконструировать объект BooksList.
```
bl:=BooksList{
     Content: books
}
```

2024-02-23 06:37 UTC, vladislavmass commented on hw09_serialize/main.go
> +func DeserializationPROTO(books *BooksList, data []byte) []*Book {
Зачем тут `books *BooksList`? Лучше сделать функцию с сигнатурой `func DeserializationPROTO( data []byte) []*Book ` . А уже внутри метода создать объект

2024-02-25 07:04 UTC, vladislavmass commented on hw09_serialize/main.go
> +	books := []Book{
Что бы получить слайс указателей на Book,  измените эту строку следующим образом `books := []*Book{`

2024-02-28 06:04 UTC, vladislavmass approved these changes

2024-03-06 15:46 UTC, merged