done
fi1atov/go_otus_hw pull request #9
Opened 2024-03-12 11:48 UTC by fi1atov

## Домашнее задание №10 «Обработка данных сенсора движения»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~80 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-03-13 03:37 UTC, vladislavmass requested changes

2024-03-13 03:37 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	time.Sleep(60 * time.Second)
1 минута это время за которое должно произойти считывание данных, а не завершится работа всей програмы. Тоесть 1 минуты должна отрабатывать только go рутина writeInChannel, а остальные работают столько, сколько им надо

2024-03-13 03:37 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		fmt.Println("Get from channel 10 elems into slice: ", dataSlice)
Почему метод обработки данных вообще что то пишет в консоль? Это можно применять для отладки, но не более того

2024-03-13 03:37 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		dataSlice := make([]int, 0, 10)
Зачем нам нужен слайс если хватить счетчика и аккумулятора?

2024-03-13 03:37 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		time.Sleep(1 * time.Second)
Не понимаю зачем этому методу спать 1 секунду

2024-03-13 03:37 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +func printAverage(channelProcessed chan int) {
Этот метод не должен работать в отдельном потоке, его можно запустить и в main потоке

2024-03-13 14:46 UTC, fi1atov commented on hw10_motion_sensor/main.go
> +		time.Sleep(1 * time.Second)
Убрал

2024-03-13 14:46 UTC, fi1atov commented on hw10_motion_sensor/main.go
> +		fmt.Println("Get from channel 10 elems into slice: ", dataSlice)
Убрал

2024-03-13 14:50 UTC, fi1atov commented on hw10_motion_sensor/main.go
> +func printAverage(channelProcessed chan int) {
Тогда бесконечный цикл этой функции будет крутить внутри main() и time.Sleep() на 60 секунд не сработает. Программа будет крутиться вечно. Пробую добавить использование select в main чтобы решить эту проблему

2024-03-13 18:53 UTC, vladislavmass requested changes

2024-03-13 18:53 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	for {
А зачем тут бесконечный for. Тут лучше использовать range for chanel. Выход из него произойдет по закрытию канала

2024-03-14 20:29 UTC, vladislavmass approved these changes

2024-03-16 20:02 UTC, merged